name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build

  deploy:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notify_success:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0x00ff00
          nodetail: true
          title: '**:white_check_mark: Deployment successful!** A new version deployed to production'
          description: |
            ### Deployment Details
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
          username: 'Mr Notification Robot Person Thing'

  notify_failure:
    needs: [build_and_test, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0xff0000
          nodetail: true
          title: '**:x: Build failed!** The pipeline encountered an error'
          description: |
            ### Failure Details
            **Repository:** ${{ github.base_ref }}
            **Branch:** ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message }}
            **Author:** ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login || github.event.head_commit.author.name }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ github.job }}

            [View Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            [View Workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          username: 'Mr Notification Robot Person Thing'
